### ISSUE TITLE
remote.Watch can't support one local actor monitor many actor in the same remote endpoint

### ISSUE THREAD

**Issue by alex023** [AsynkronIT/protoactor-go#172]
We are using proctor in our business.But in some complex scene , there are some problem in remote.Watch

## Problem Description:
 We can provide a simplified large-scale chat room to simulate the scene of the problem。Many users share in topics through serval proxy servers in the chat server . We must support：
- Feature1：Normally, notify a user published message to other online users.
- Feature2：restart Chat Server，Proxy Server Actor can monitor ,and reconnect after Chat Server restarted 。
- Feature3：One Proxy Server shutdown，Topic[Actor]can monitor and refresh “online member list”.
- Feature4：User disconnect,Topic[Actor]can monitor, and move it from “online member list”。

The flow picture show the topology we want:
![image](https://user-images.githubusercontent.com/12086891/30173152-5f2331e6-9429-11e7-89d2-ce05867a3f16.png)
 Topic is Actor, we use `Watch`to monitor whether the Agent[Actor] is alive, the code just like `examples/chat/server`：
```go
func notifyAll(clients *hashset.Set, message interface{}) {
	fmt.Printf("send msg %v %d client\n",message,clients.Size())
	for _, tmp := range clients.Values() {
		client := tmp.(*actor.PID)
		client.Tell(message)
	}
}

func main() {
	remote.Start("127.0.0.1:8080")
	clients := hashset.New()
	props := actor.FromFunc(func(context actor.Context) {
		switch msg := context.Message().(type) {
		case *actor.Started:
			println("room is started!")
		case *actor.Stopping:
			println("room is stopping!")

		case *messages.Connect:
			clients.Add(msg.Sender)
			msg.Sender.Tell(&messages.Connected{Message: "Welcome!"})
			fmt.Println("server Watch client actor")
			context.Watch(msg.Sender)
		case *actor.Terminated:
			//want remove it from online member list,when the agent[/the node] is disconnect
			clients.Remove(msg.Who)
		case *messages.SayRequest:
			notifyAll(clients, &messages.SayResponse{
				UserName: msg.UserName,
				Message:  msg.Message,
			})
		case *messages.NickRequest:
			notifyAll(clients, &messages.NickResponse{
				OldUserName: msg.OldUserName,
				NewUserName: msg.NewUserName,
			})
		}
	})
	remote.Register("room",props)
	console.ReadLine()
}
```
### For Feature3:
When the proxy server shutdown, the Chat Server still try to send the message to the Agent[Actor] in the proxy server.It can not monitor some agent[Actor] are terminated.
![image](https://user-images.githubusercontent.com/12086891/30173185-77e7ecc6-9429-11e7-9216-0aab2769be8d.png)
In endpoint_watcher.go,the struct endpointWatcher just store only one remote actor.PID.
```
type endpointWatcher struct {
	address string          //<—Same the endpoint
	watched map[string]*actor.PID //<—one actor just watch only one remote actor
}
```
when a new remote actor was watch by local actor, the watched will reset to a new actor PID.and the older PID is throw away。
And now, the proxy 1  shutdown, the endpointWatcher just notify the newer remote actor is terminated.
And when this proxy server restart, the client can not connect the Chat Server ,because the endpointWatcher call ctx.SetBehavior(state.Terminated).
 
### For Feature4:
When the actor is disconnect, the Chat Server Topic can not determine.
![image](https://user-images.githubusercontent.com/12086891/30173204-81f8279e-9429-11e7-82e3-1e0078bcb0a5.png)
endpointWatcher can receive remoteTerminate event, but the watchee ptr is not the same as the previous cache in watched.
The source code:
```
case *remoteTerminate:
	delete(state.watched, msg.Watcher.Id)
	terminated := &actor.Terminated{
				Who:               msg.Watchee,    //<—msg.Watchee ptr is not same as  localcontext.watching in local_context.go 
				AddressTerminated: false,
			}
	ref, ok := actor.ProcessRegistry.GetLocal(msg.Watcher.Id)
	if ok {
		ref.SendSystemMessage(msg.Watcher, terminated)
	}
```
So, is connect sequence is A、B、C, the  actor of A ptr is lost.

## Suggest:
If we have no problem with the understanding of the Watch, I think remote_watcher.go should be refactored. 
1. endpointWatcher.watched should is ”map[string]map[string]*actor.PID”.

just like: ```
type endpointWatcher struct {
	address string
	watched map[string]*watchedPIDs //key is the watching PID string, value is the watched PIDs
}

type watchedPIDs struct {
	pids map[string]*actor.PID  
}

func (wps *watchedPIDs) add(pid *actor.PID) {
	if wps.pids == nil {
		wps.pids = make(map[string]*actor.PID)
	}
	wps.pids[pid.Id] = pid
}
func (wps *watchedPIDs)get(id string)(*actor.PID,bool){
	pid,founded:=wps.pids[id]
	return pid,founded
}
func (wps *watchedPIDs) remove(pid *actor.PID) {
	delete(wps.pids, pid.Id)
	if len(wps.pids) == 0 {
		wps.pids = nil
	}
}
func (wps *watchedPIDs) all() []*actor.PID {
	var result []*actor.PID
	for _, pid := range wps.pids {
		result = append(result, pid)
	}
	return result
}
func (wps *watchedPIDs) clean() {
	wps.pids = nil
}
func (wps *watchedPIDs) size() int {
	if wps.pids == nil {
		return 0
	} else {
		return len(wps.pids)
	}

}

```
2. do not use ctx.SetBehavior(state.Terminated)
after call this function, it can not Watch again when  the remote server restarted.

## Finally:
We continue to debug further to avoid missing.
I want to know if there is an error in use in the above scenario， please give some comments.
If ok, we can pull the request about an week later.

**Comment by alex023** [comment]
test code:
[demo code](https://github.com/alex023/tmp_watchremote)

**Comment by PotterDai** [comment]
This is a real problem, a terminated endpoint-watcher will never be restarted even if the endpoint itself restarts.

**Comment by PotterDai** [comment]
It seems in dotnet version the problem has been solved, please check:
https://github.com/AsynkronIT/protoactor-dotnet/pull/302

**Comment by alex023** [comment]
@PotterDai 
I am not familiar with c#, and just only browse to  learn. I think the fix resolve Endpoint_Watch state change (Terminatd->Receive) in cluster。But the bug still exists:
1. multi-Watcher to multi-Watchee when remoting
2. remote watcher still cannot  re-alive without cluster

btw, In order to confirm my use of the scene is correct, I deliberately learned scala and akka these days . No similar problems have occurred.

**Comment by PotterDai** [comment]
@alex023 
Hmmm... I see. **Actor(@_NodeA_)** cannot watch both **Actor1(@_NodeB_)**, **Actor2(@_NodeB_)** at the same time since at **Endpoint(@_NodeB_)**, there is only one watching spot for **Actor(@_NodeA_)**.  Am I right?

**Comment by PotterDai** [comment]
@alex023 
Hmmm...now I understand. **Watcher(@_NodeA_)** cannot watch both **Watchee1(@_NodeB_)**, **Watchee2(@_NodeB_)**, since at **EndpointNodeB(@_NodeA_)**, it has only one watching spot for **Watcher(@_NodeA_)**. Am I right?

**Comment by rogeralsing** [comment]
Closing due to inactivity. Reopen if still relevant.
