### ISSUE TITLE
Supervision nil pointer error

### ISSUE THREAD

**Issue by tobowers** [AsynkronIT/protoactor-go#289]
```
12:28 ~/code/go/src/github.com/AsynkronIT/protoactor-go (dev) $ go get ./...
13:56 ~/code/go/src/github.com/AsynkronIT/protoactor-go (dev) $ cd examples/supervision/
13:56 ~/code/go/src/github.com/AsynkronIT/protoactor-go/examples/supervision (dev) $ go run main.go 
Starting, initialize actor here
Hello Roger
2019/03/13 12:57:02 [MAILBOX] [ACTOR] Recovering actor="nonhost/$1/$2"Stopping, actor is about to shut down
 Stopped, actor and its children are stopped
reason="Ouch" stacktrace="main.(*childActor).Receive:40" 
2019/03/13 12:57:02 [MAILBOX] [ACTOR] Recovering actor="nonhost/$1" reason="runtime error: invalid memory address or nil pointer dereference" stacktrace="github.com/AsynkronIT/protoactor-go/actor.(*actorContext).handleFailure:501" 
2019/03/13 12:57:02 [ACTOR] [SUPERVISION] actor="nonhost/$1" directive="RestartDirective" reason="runtime error: invalid memory address or nil pointer dereference" 
```

I noticed this in our app when upgrading to the tip of dev, I went into the examples to see what was happening and found that it happens here too. I'm still looking into what's happening. It appears that the supervisor isn't actually getting attached to the context and triggering a nil here:

https://github.com/AsynkronIT/protoactor-go/blob/dev/actor/actor_context.go#L501

**Comment by tobowers** [comment]
git bisect shows me this is the first commit with this error: https://github.com/AsynkronIT/protoactor-go/commit/25625073b53ee26430856570008f011c89a3ee83

**Comment by tobowers** [comment]
I'm having trouble figuring out how an actor ever fulfills the SupervisorStrategy interface or an actor_context gets its supervisor set.

**Comment by otherview** [comment]
Can you post a code snippet ?

**Comment by PotterDai** [comment]
@tobowers Thank you for bringing it up!
This was a very embarrassing mistake for me. Fixed right the way!

**Comment by tobowers** [comment]
> Can you post a code snippet ?

This is just running the supervision example in this repo. Check out #291

**Comment by PotterDai** [comment]
@tobowers @otherview 
Should have been fixed here: https://github.com/AsynkronIT/protoactor-go/pull/291 =)

**Comment by tobowers** [comment]
Thank you for the quick fix!

**Comment by tobowers** [comment]
@PotterDai we're still seeing these nil pointers on the higher level actors (the parents of the one with a supervisor). I *think* this should use the getSupervisor() method of props instead? If there is no supervisor it should go up the chain?

**Comment by potterdai** [comment]
@tobowers Hi, that's right! It has been fixed here https://github.com/AsynkronIT/protoactor-go/pull/295
